services:
  app:
    image: ghcr.io/nils-witt/pg-server
    volumes:
      - ./dgm1_tiff_kacheln:/dgm1_tiff_kacheln
  frontend:
    image: ghcr.io/nils-witt/pg-frontend
  proxy:
    image: nginx:latest
    ports:
      - 80:80
    volumes:
      - ./proxy/nginx.conf:/etc/nginx/conf.d/default.conf
    depends_on:
      - frontend
      - app